language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t cmizudg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cmizudg/docker-react npm run test